<?php

return [
    'auth' => [
        'single_session' => env('SWIFTFLITZ_SINGLE_SESSION', false),
        'mode' => env('SWIFTFLITZ_AUTH_MODE', 'token'), // 'token' or 'session'
        'token_expiration_days' => env('SWIFTFLITZ_TOKEN_EXPIRATION_DAYS', 7),
    ],
    'permissions' => [
        'super_admin' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.view_analytics' => 'View detailed analytics',
            ],
            'rentals' => [
                'rentals.view_all' => 'View all rentals',
                'rentals.view_own' => 'View own rentals only',
                'rentals.create' => 'Create new rental',
                'rentals.edit' => 'Edit rental details',
                'rentals.delete' => 'Delete rentals',
                'rentals.mark_returned' => 'Mark vehicle as returned',
                'rentals.approve_return' => 'Approve return inspection',
                'rentals.add_charges' => 'Add additional charges',
                'rentals.update_status' => 'Change rental status',
                'rentals.view_quotes' => 'View quote requests',
                'rentals.manage_quotes' => 'Respond to quotes',
                'rentals.export' => 'Export rental data',
                'rentals.view_documents' => 'View pickup/return docs',
                'rentals.view_inspections' => 'View rental inspection log',
                'rentals.manage_additional_charges' => 'Manage additional charges catalog',
                'rentals.manage_active' => 'Manage active rentals',
                'rentals.manage_pending_bookings' => 'Manage pending bookings',
                'rentals.manage_overdue' => 'Manage overdue rentals',
                'rentals.manage_pending_approval' => 'Manage pending approvals',
                'rentals.manage_security_deposit' => 'Manage security deposits',
                'rentals.process_pickup' => 'Process vehicle pickup',
                'rentals.manage_locations' => 'Manage rental pickup locations',
                'rentals.send_payment_link' => 'Send payment link to customer',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
                'vehicles.create' => 'Add new vehicle',
                'vehicles.edit' => 'Edit vehicle details',
                'vehicles.delete' => 'Delete vehicles',
                'vehicles.manage_availability' => 'Change availability',
                'vehicles.manage_pricing' => 'Set/edit pricing',
                'vehicles.toggle_price_visibility' => 'Show/hide prices',
                'vehicles.manage_maintenance' => 'Maintenance tracking',
                'vehicles.manage_insurance' => 'Insurance info',
                'vehicles.manage_categories' => 'Manage categories',
                'vehicles.manage_features' => 'Manage features',
                'vehicles.export' => 'Export vehicle data',
                'vehicles.manage_available' => 'View available vehicles',
                'vehicles.manage_rented' => 'View rented vehicles',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.create' => 'Add new customer',
                'customers.edit' => 'Edit customer info',
                'customers.delete' => 'Delete customers',
                'customers.view_history' => 'View rental history',
                'customers.view_documents' => 'View documents',
                'customers.blacklist' => 'Blacklist customers',
                'customers.export' => 'Export customer data',
                'customers.manage_license_expired' => 'View license expired customers',
                'customers.manage_license_expiring' => 'View license expiring customers',
            ],
            'reports' => [
                'reports.view_all' => 'Access all reports',
                'reports.view_revenue' => 'View revenue reports',
                'reports.view_utilization' => 'Vehicle utilization',
                'reports.view_manager_performance' => 'Manager performance',
                'reports.view_outstanding_payments' => 'Outstanding payments',
                'reports.view_maintenance' => 'Maintenance reports',
                'reports.view_customer_analytics' => 'Customer analytics',
                'reports.export_pdf' => 'Export to PDF',
                'reports.export_excel' => 'Export to Excel',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
                'notifications.delete' => 'Delete notifications',
                'notifications.manage_settings' => 'Manage settings',
            ],
            'users_access' => [
                'users.view_all' => 'View all users',
                'users.create' => 'Create new user',
                'users.edit' => 'Edit user details',
                'users.delete' => 'Delete users',
                'users.assign_roles' => 'Assign roles',
                'users.impersonate' => 'Impersonate users',
                'roles.view_all' => 'View all roles',
                'roles.create' => 'Create custom role',
                'roles.edit' => 'Edit role permissions',
                'roles.delete' => 'Delete roles',
                'activity_logs.view' => 'View activity logs',
                'sessions.manage' => 'Manage user sessions',
            ],
            'settings' => [
                'settings.view_general' => 'View general settings',
                'settings.edit_general' => 'Edit general settings',
                'settings.edit_rental' => 'Edit rental settings',
                'settings.edit_pricing' => 'Edit pricing settings',
                'settings.edit_email' => 'Email configuration',
                'settings.edit_whatsapp' => 'WhatsApp configuration',
                'settings.edit_whatsapp_templates' => 'Manage WhatsApp templates',
                'settings.edit_sms' => 'SMS configuration',
                'settings.edit_sms_templates' => 'Manage SMS templates',
                'settings.edit_payment' => 'Payment settings',
                'settings.view_backup' => 'View backup status',
                'settings.manage_backup' => 'Manage backups',
                'settings.edit_backup' => 'Edit backup schedule settings',
                'settings.delete_backup' => 'Delete backup files',
                'settings.view_logs' => 'View system logs',
                'settings.clear_cache' => 'Clear cache',
                'settings.manage_security_deposit' => 'Manage security deposit settings',
                'settings.test_email' => 'Send test email',
                'settings.test_whatsapp' => 'Send test WhatsApp message',
                'settings.test_sms' => 'Send test SMS',
                'settings.view_seo' => 'View SEO settings',
                'settings.edit_seo' => 'Edit SEO settings',
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
                'branches.create' => 'Create new branch',
                'branches.edit' => 'Edit branch details',
                'branches.delete' => 'Delete branches',
                'branches.manage_members' => 'Manage branch members',
            ],
            'coupons' => [
                'coupons.view_all' => 'View all coupons',
                'coupons.create' => 'Create new coupon',
                'coupons.edit' => 'Edit coupon details',
                'coupons.delete' => 'Delete coupons',
            ],
            'discounts' => [
                'discounts.view_all' => 'View all discount rules',
                'discounts.create' => 'Create new discount rule',
                'discounts.edit' => 'Edit discount rule',
                'discounts.delete' => 'Delete discount rules',
            ],
            'exports' => [
                'exports.download_rentals' => 'Download rental exports',
                'exports.download_vehicles' => 'Download vehicle exports',
                'exports.download_customers' => 'Download customer exports',
                'exports.download_reports' => 'Download report exports',
                'exports.download_all' => 'Download any export',
            ],
            'website' => [
                'website.edit_homepage' => 'Edit homepage',
                'website.edit_about' => 'Edit about page',
                'website.edit_contact' => 'Edit contact page',
                'website.manage_testimonials' => 'Manage testimonials',
                'website.view_subscribers' => 'View subscribers',
                'website.manage_static_pages' => 'Manage static pages',
                'website.edit_policies' => 'Edit T&C/Privacy',
                'website.manage_faq' => 'Manage FAQs',
            ],
            'drivers' => [
                'drivers.view_all' => 'View all drivers',
                'drivers.create' => 'Add new driver',
                'drivers.edit' => 'Edit driver details',
                'drivers.delete' => 'Delete drivers',
            ],
            'fleet_vehicles' => [
                'fleet_vehicles.view_all' => 'View all fleet vehicles',
                'fleet_vehicles.create' => 'Add new fleet vehicle',
                'fleet_vehicles.edit' => 'Edit fleet vehicle details',
                'fleet_vehicles.delete' => 'Delete fleet vehicles',
            ],
            'airport_transfer' => [
                'airport_transfer.view_all' => 'View airports & locations',
                'airport_transfer.create' => 'Create airports',
                'airport_transfer.edit' => 'Edit airports',
                'airport_transfer.delete' => 'Delete airports & locations',
                'airport_transfer.manage_active' => 'Toggle active status',
                'airport_transfer.airport_packages' => 'Manage packages & pricing',
                'airport_transfer.airport_locations' => 'Manage airport locations',
                'airport_transfer.airport_vehicles' => 'Manage airport vehicles',
                'airport_transfer.manage_bookings' => 'Manage airport bookings',
                'airport_transfer.manage_pending_bookings' => 'Manage pending bookings',
                'airport_transfer.manage_approval' => 'Approve airport transfers',
            ],
            'chauffeur_rental' => [
                'chauffeur_rental.view_all' => 'View all chauffeur bookings',
                'chauffeur_rental.create' => 'Create chauffeur booking',
                'chauffeur_rental.edit' => 'Edit chauffeur booking',
                'chauffeur_rental.delete' => 'Delete chauffeur booking',
                'chauffeur_rental.manage_bookings' => 'Manage chauffeur bookings',
                'chauffeur_rental.manage_customers' => 'Manage chauffeur customers',
                'chauffeur_rental.manage_locations' => 'Manage chauffeur locations',
                'chauffeur_rental.manage_settings' => 'Manage chauffeur settings',
            ],
            'transactions' => [
                'transactions.view_all' => 'View all payment transactions',
                'transactions.export' => 'Export transaction data',
                'transactions.resolve' => 'Manually resolve under-review payment transactions',
            ],
        ],

        'admin' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.view_analytics' => 'View detailed analytics',
            ],
            'rentals' => [
                'rentals.view_all' => 'View all rentals',
                'rentals.view_own' => 'View own rentals only',
                'rentals.create' => 'Create new rental',
                'rentals.edit' => 'Edit rental details',
                'rentals.delete' => 'Delete rentals',
                'rentals.mark_returned' => 'Mark vehicle as returned',
                'rentals.approve_return' => 'Approve return inspection',
                'rentals.add_charges' => 'Add additional charges',
                'rentals.update_status' => 'Change rental status',
                'rentals.view_quotes' => 'View quote requests',
                'rentals.manage_quotes' => 'Respond to quotes',
                'rentals.export' => 'Export rental data',
                'rentals.view_documents' => 'View pickup/return docs',
                'rentals.view_inspections' => 'View rental inspection log',
                'rentals.manage_additional_charges' => 'Manage additional charges catalog',
                'rentals.manage_active' => 'Manage active rentals',
                'rentals.manage_pending_bookings' => 'Manage pending bookings',
                'rentals.manage_overdue' => 'Manage overdue rentals',
                'rentals.manage_pending_approval' => 'Manage pending approvals',
                'rentals.manage_security_deposit' => 'Manage security deposits',
                'rentals.process_pickup' => 'Process vehicle pickup',
                'rentals.manage_locations' => 'Manage rental pickup locations',
                'rentals.send_payment_link' => 'Send payment link to customer',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
                'vehicles.create' => 'Add new vehicle',
                'vehicles.edit' => 'Edit vehicle details',
                'vehicles.delete' => 'Delete vehicles',
                'vehicles.manage_availability' => 'Change availability',
                'vehicles.manage_pricing' => 'Set/edit pricing',
                'vehicles.toggle_price_visibility' => 'Show/hide prices',
                'vehicles.manage_maintenance' => 'Maintenance tracking',
                'vehicles.manage_insurance' => 'Insurance info',
                'vehicles.manage_categories' => 'Manage categories',
                'vehicles.manage_features' => 'Manage features',
                'vehicles.export' => 'Export vehicle data',
                'vehicles.manage_available' => 'View available vehicles',
                'vehicles.manage_rented' => 'View rented vehicles',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.create' => 'Add new customer',
                'customers.edit' => 'Edit customer info',
                'customers.delete' => 'Delete customers',
                'customers.view_history' => 'View rental history',
                'customers.view_documents' => 'View documents',
                'customers.blacklist' => 'Blacklist customers',
                'customers.export' => 'Export customer data',
                'customers.manage_license_expired' => 'View license expired customers',
                'customers.manage_license_expiring' => 'View license expiring customers',
            ],
            'reports' => [
                'reports.view_all' => 'Access all reports',
                'reports.view_revenue' => 'View revenue reports',
                'reports.view_utilization' => 'Vehicle utilization',
                'reports.view_manager_performance' => 'Manager performance',
                'reports.view_outstanding_payments' => 'Outstanding payments',
                'reports.view_maintenance' => 'Maintenance reports',
                'reports.view_customer_analytics' => 'Customer analytics',
                'reports.export_pdf' => 'Export to PDF',
                'reports.export_excel' => 'Export to Excel',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
                'notifications.delete' => 'Delete notifications',
                'notifications.manage_settings' => 'Manage settings',
            ],
            'users_access' => [
                'users.view_all' => 'View all users',
                'users.create' => 'Create new user',
                'users.edit' => 'Edit user details',
                'users.delete' => 'Delete users',
                'users.assign_roles' => 'Assign roles',
                'roles.view_all' => 'View all roles',
                'roles.create' => 'Create custom role',
                'roles.edit' => 'Edit role permissions',
                'roles.delete' => 'Delete roles',
                'activity_logs.view' => 'View activity logs',
                'sessions.manage' => 'Manage user sessions',
            ],
            'settings' => [
                'settings.view_general' => 'View general settings',
                'settings.edit_general' => 'Edit general settings',
                'settings.edit_rental' => 'Edit rental settings',
                'settings.edit_pricing' => 'Edit pricing settings',
                'settings.edit_email' => 'Email configuration',
                // 'settings.edit_whatsapp' => 'WhatsApp configuration',
                'settings.edit_whatsapp_templates' => 'Manage WhatsApp templates',
                // 'settings.edit_sms' => 'SMS configuration',
                'settings.edit_sms_templates' => 'Manage SMS templates',
                // 'settings.edit_payment' => 'Payment settings',
                'settings.manage_security_deposit' => 'Manage security deposit settings',
                // 'settings.test_email' => 'Send test email',
                // 'settings.test_whatsapp' => 'Send test WhatsApp message',
                // 'settings.test_sms' => 'Send test SMS',
                /* Excluded backups and logs */
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
                'branches.create' => 'Create new branch',
                'branches.edit' => 'Edit branch details',
                'branches.delete' => 'Delete branches',
                'branches.manage_members' => 'Manage branch members',
            ],
            'coupons' => [
                'coupons.view_all' => 'View all coupons',
                'coupons.create' => 'Create new coupon',
                'coupons.edit' => 'Edit coupon details',
                'coupons.delete' => 'Delete coupons',
            ],
            'discounts' => [
                'discounts.view_all' => 'View all discount rules',
                'discounts.create' => 'Create new discount rule',
                'discounts.edit' => 'Edit discount rule',
                'discounts.delete' => 'Delete discount rules',
            ],
            'exports' => [
                'exports.download_rentals' => 'Download rental exports',
                'exports.download_vehicles' => 'Download vehicle exports',
                'exports.download_customers' => 'Download customer exports',
                'exports.download_reports' => 'Download report exports',
                'exports.download_all' => 'Download any export',
            ],
            'website' => [
                'website.edit_homepage' => 'Edit homepage',
                'website.edit_about' => 'Edit about page',
                'website.edit_contact' => 'Edit contact page',
                'website.manage_testimonials' => 'Manage testimonials',
                'website.view_subscribers' => 'View subscribers',
                'website.manage_static_pages' => 'Manage static pages',
                'website.edit_policies' => 'Edit T&C/Privacy',
                'website.manage_faq' => 'Manage FAQs',
            ],
            'drivers' => [
                'drivers.view_all' => 'View all drivers',
                'drivers.create' => 'Add new driver',
                'drivers.edit' => 'Edit driver details',
                'drivers.delete' => 'Delete drivers',
            ],
            'fleet_vehicles' => [
                'fleet_vehicles.view_all' => 'View all fleet vehicles',
                'fleet_vehicles.create' => 'Add new fleet vehicle',
                'fleet_vehicles.edit' => 'Edit fleet vehicle details',
                'fleet_vehicles.delete' => 'Delete fleet vehicles',
            ],
            'airport_transfer' => [
                'airport_transfer.view_all' => 'View airports & locations',
                'airport_transfer.create' => 'Create airports',
                'airport_transfer.edit' => 'Edit airports',
                'airport_transfer.delete' => 'Delete airports & locations',
                'airport_transfer.manage_active' => 'Toggle active status',
                'airport_transfer.airport_packages' => 'Manage packages & pricing',
                'airport_transfer.airport_locations' => 'Manage airport locations',
                'airport_transfer.airport_vehicles' => 'Manage airport vehicles',
                'airport_transfer.manage_bookings' => 'Manage airport bookings',
                'airport_transfer.manage_pending_bookings' => 'Manage pending bookings',
                'airport_transfer.manage_approval' => 'Approve airport transfers',
            ],
            'chauffeur_rental' => [
                'chauffeur_rental.view_all' => 'View all chauffeur bookings',
                'chauffeur_rental.create' => 'Create chauffeur booking',
                'chauffeur_rental.edit' => 'Edit chauffeur booking',
                'chauffeur_rental.delete' => 'Delete chauffeur booking',
                'chauffeur_rental.manage_bookings' => 'Manage chauffeur bookings',
                'chauffeur_rental.manage_customers' => 'Manage chauffeur customers',
                'chauffeur_rental.manage_locations' => 'Manage chauffeur locations',
                'chauffeur_rental.manage_settings' => 'Manage chauffeur settings',
            ],
            'transactions' => [
                'transactions.view_all' => 'View all payment transactions',
                'transactions.export' => 'Export transaction data',
                'transactions.resolve' => 'Manually resolve under-review payment transactions',
            ],

        ],

        'manager' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.view_analytics' => 'View detailed analytics',
            ],
            'rentals' => [
                'rentals.view_all' => 'View all rentals',
                'rentals.view_own' => 'View own rentals only',
                'rentals.create' => 'Create new rental',
                'rentals.mark_returned' => 'Mark vehicle as returned',
                'rentals.approve_return' => 'Approve return inspection',
                'rentals.add_charges' => 'Add additional charges',
                'rentals.update_status' => 'Change rental status',
                'rentals.view_quotes' => 'View quote requests',
                'rentals.manage_quotes' => 'Respond to quotes',
                'rentals.export' => 'Export rental data',
                'rentals.view_documents' => 'View pickup/return docs',
                'rentals.view_inspections' => 'View rental inspection log',
                'rentals.manage_additional_charges' => 'Manage additional charges catalog',
                'rentals.manage_active' => 'Manage active rentals',
                'rentals.manage_pending_bookings' => 'Manage pending bookings',
                'rentals.manage_overdue' => 'Manage overdue rentals',
                'rentals.manage_pending_approval' => 'Manage pending approvals',
                'rentals.manage_security_deposit' => 'Manage security deposits',
                'rentals.process_pickup' => 'Process vehicle pickup',
                'rentals.manage_locations' => 'Manage rental pickup locations',
                'rentals.send_payment_link' => 'Send payment link to customer',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
                'vehicles.create' => 'Add new vehicle',
                'vehicles.edit' => 'Edit vehicle details',
                'vehicles.manage_availability' => 'Change availability',
                'vehicles.manage_pricing' => 'Set/edit pricing',
                'vehicles.toggle_price_visibility' => 'Show/hide prices',
                'vehicles.manage_maintenance' => 'Maintenance tracking',
                'vehicles.manage_insurance' => 'Insurance info',
                'vehicles.manage_categories' => 'Manage categories',
                'vehicles.manage_features' => 'Manage features',
                'vehicles.export' => 'Export vehicle data',
                'vehicles.manage_available' => 'View available vehicles',
                'vehicles.manage_rented' => 'View rented vehicles',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.create' => 'Add new customer',
                'customers.edit' => 'Edit customer info',
                'customers.view_history' => 'View rental history',
                'customers.view_documents' => 'View documents',
                'customers.blacklist' => 'Blacklist customers',
                'customers.export' => 'Export customer data',
                'customers.manage_license_expired' => 'View license expired customers',
                'customers.manage_license_expiring' => 'View license expiring customers',
            ],
            'reports' => [
                'reports.view_all' => 'Access all reports',
                'reports.view_revenue' => 'View revenue reports',
                'reports.view_utilization' => 'Vehicle utilization',
                'reports.view_outstanding_payments' => 'Outstanding payments',
                'reports.view_maintenance' => 'Maintenance reports',
                'reports.view_customer_analytics' => 'Customer analytics',
                'reports.export_pdf' => 'Export to PDF',
                'reports.export_excel' => 'Export to Excel',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
                'notifications.delete' => 'Delete notifications',
                'notifications.manage_settings' => 'Manage settings',
            ],
            'settings' => [
                'settings.view_general' => 'View general settings',
                'settings.edit_rental' => 'Edit rental settings',
                'settings.edit_pricing' => 'Edit pricing settings',
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
            ],
            'coupons' => [
                'coupons.view_all' => 'View all coupons',
                'coupons.create' => 'Create new coupon',
                'coupons.edit' => 'Edit coupon details',
            ],
            'discounts' => [
                'discounts.view_all' => 'View all discount rules',
                'discounts.create' => 'Create new discount rule',
                'discounts.edit' => 'Edit discount rule',
                'discounts.delete' => 'Delete discount rules',
            ],
            'exports' => [
                'exports.download_rentals' => 'Download rental exports',
                'exports.download_vehicles' => 'Download vehicle exports',
                'exports.download_customers' => 'Download customer exports',
                'exports.download_reports' => 'Download report exports',
            ],
            'website' => [
                'website.edit_homepage' => 'Edit homepage',
                'website.edit_about' => 'Edit about page',
                'website.edit_contact' => 'Edit contact page',
                'website.manage_testimonials' => 'Manage testimonials',
                'website.view_subscribers' => 'View subscribers',
                'website.manage_static_pages' => 'Manage static pages',
                'website.manage_faq' => 'Manage FAQs',
            ],
            'fleet_vehicles' => [
                'fleet_vehicles.view_all' => 'View all fleet vehicles',
                'fleet_vehicles.create' => 'Add new fleet vehicle',
                'fleet_vehicles.edit' => 'Edit fleet vehicle details',
                'fleet_vehicles.delete' => 'Delete fleet vehicles',
            ],
            'airport_transfer' => [
                'airport_transfer.view_all' => 'View airports & locations',
                'airport_transfer.create' => 'Create airports',
                'airport_transfer.edit' => 'Edit airports',
                'airport_transfer.manage_active' => 'Toggle active status',
                'airport_transfer.airport_packages' => 'Manage packages & pricing',
                'airport_transfer.airport_locations' => 'Manage airport locations',
                'airport_transfer.manage_bookings' => 'Manage airport bookings',
                'airport_transfer.manage_pending_bookings' => 'Manage pending bookings',
            ],
        ],

        'staff' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
            ],
            'rentals' => [
                'rentals.view_own' => 'View own rentals only',
                'rentals.create' => 'Create new rental',
                'rentals.mark_returned' => 'Mark vehicle as returned',
                'rentals.update_status' => 'Change rental status',
                'rentals.view_quotes' => 'View quote requests',
                'rentals.view_documents' => 'View pickup/return docs',
                'rentals.manage_active' => 'Manage active rentals',
                'rentals.manage_pending_bookings' => 'Manage pending bookings',
                'rentals.manage_overdue' => 'Manage overdue rentals',
                'rentals.process_pickup' => 'Process vehicle pickup',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
                'vehicles.manage_availability' => 'Change availability',
                'vehicles.manage_maintenance' => 'Maintenance tracking',
                'vehicles.manage_available' => 'View available vehicles',
                'vehicles.manage_rented' => 'View rented vehicles',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.create' => 'Add new customer',
                'customers.edit' => 'Edit customer info',
                'customers.view_history' => 'View rental history',
                'customers.view_documents' => 'View documents',
                'customers.manage_license_expired' => 'View license expired customers',
                'customers.manage_license_expiring' => 'View license expiring customers',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
                'notifications.delete' => 'Delete notifications',
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
            ],
        ],

        'accountant' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
                'dashboard.view_analytics' => 'View detailed analytics',
            ],
            'rentals' => [
                'rentals.view_all' => 'View all rentals',
                'rentals.export' => 'Export rental data',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
                'vehicles.export' => 'Export vehicle data',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.view_history' => 'View rental history',
                'customers.export' => 'Export customer data',
            ],
            'reports' => [
                'reports.view_all' => 'Access all reports',
                'reports.view_revenue' => 'View revenue reports',
                'reports.view_utilization' => 'Vehicle utilization',
                'reports.view_outstanding_payments' => 'Outstanding payments',
                'reports.view_maintenance' => 'Maintenance reports',
                'reports.view_customer_analytics' => 'Customer analytics',
                'reports.export_pdf' => 'Export to PDF',
                'reports.export_excel' => 'Export to Excel',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
                'notifications.delete' => 'Delete notifications',
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
            ],
            'exports' => [
                'exports.download_rentals' => 'Download rental exports',
                'exports.download_vehicles' => 'Download vehicle exports',
                'exports.download_customers' => 'Download customer exports',
                'exports.download_reports' => 'Download report exports',
            ],
        ],

        'viewer' => [
            'dashboard' => [
                'dashboard.view' => 'View dashboard',
            ],
            'rentals' => [
                'rentals.view_all' => 'View all rentals',
                'rentals.view_quotes' => 'View quote requests',
                'rentals.view_documents' => 'View pickup/return docs',
            ],
            'vehicles' => [
                'vehicles.view_all' => 'View all vehicles',
            ],
            'customers' => [
                'customers.view_all' => 'View all customers',
                'customers.view_history' => 'View rental history',
            ],
            'reports' => [
                'reports.view_all' => 'Access all reports',
                'reports.view_revenue' => 'View revenue reports',
                'reports.view_utilization' => 'Vehicle utilization',
                'reports.view_maintenance' => 'Maintenance reports',
                'reports.view_customer_analytics' => 'Customer analytics',
            ],
            'notifications' => [
                'notifications.view' => 'View notifications',
                'notifications.mark_read' => 'Mark as read',
            ],
            'branches' => [
                'branches.view_all' => 'View all branches',
            ],
            'coupons' => [
                'coupons.view_all' => 'View all coupons',
            ],
            'discounts' => [
                'discounts.view_all' => 'View all discount rules',
            ],
        ],
    ],
    'permission_groups' => [
        'dashboard' => 'Dashboard',
        'rentals' => 'Rentals',
        'vehicles' => 'Vehicles',
        'customers' => 'Customers',
        'reports' => 'Reports',
        'notifications' => 'Notifications',
        'users_access' => 'Users & Access',
        'settings' => 'Settings',
        'website' => 'Website Content',
        'branches' => 'Branches',
        'coupons' => 'Coupons',
        'discounts' => 'Discount Rules',
        'exports' => 'Exports & Downloads',
        'airport_transfer' => 'Airport Transfer',
        'fleet_vehicles' => 'Fleet Vehicles',
        'transactions' => 'Finance & Transactions',
        'chauffeur_rental' => 'Chauffeur Rental',
        'drivers' => 'Drivers',
    ],
    'media' => [
        'base_path' => env('SWIFTFLITZ_MEDIA_BASE_PATH', 'media'),
        'base_url' => env('APP_URL', 'http://localhost'),
    ],
    'uploads' => [
        // Maximum TUS upload size in bytes. Configured via SWIFTFLITZ_MAX_UPLOAD_SIZE_MB (default 20 MB).
        'max_size' => env('SWIFTFLITZ_MAX_UPLOAD_SIZE_MB', 20) * 1024 * 1024,
        // Maximum TUS upload size for video entity types (default 2 GB).
        'video_max_size' => env('SWIFTFLITZ_MAX_VIDEO_UPLOAD_SIZE_MB', 2048) * 1024 * 1024,
    ],
];
