<?php

namespace Database\Seeders;

use App\Models\WhatsAppTemplate;
use Illuminate\Database\Seeder;

class WhatsAppTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            [
                'key' => 'new_booking',
                'name' => 'New Booking Confirmation',
                'description' => 'Sent to the customer when a new booking is created.',
                'template_name' => 'booking_confirmation',
                'header' => 'Booking Confirmation',
                'body' => 'Hi {{1}}, your booking {{2}} has been confirmed. Vehicle: {{3}}. Thank you for choosing us!',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'return_reminder',
                'name' => 'Return Reminder',
                'description' => 'Sent to the customer as a reminder to return the vehicle.',
                'template_name' => 'return_reminder',
                'header' => 'Return Reminder',
                'body' => 'Reminder: Your rental {{2}} ({{3}}) is due for return on {{4}}. Please ensure timely return to avoid overdue charges. If you need an extension, contact us before the return date.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name', 'return_date'],
                'language_code' => 'en',
            ],
            [
                'key' => 'overdue_alert',
                'name' => 'Overdue Alert',
                'description' => 'Sent to the customer when a rental becomes overdue.',
                'template_name' => 'overdue_alert',
                'header' => 'Overdue Notice',
                'body' => 'OVERDUE NOTICE: Your rental {{2}} ({{3}}) was due for return and is now overdue. Please contact us immediately to avoid further charges.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'pickup_reminder',
                'name' => 'Pickup Reminder',
                'description' => 'Sent to the customer as a reminder of their upcoming vehicle pickup.',
                'template_name' => 'pickup_reminder',
                'header' => 'Pickup Reminder',
                'body' => 'Reminder: Your vehicle pickup for booking {{2}} ({{3}}) is scheduled for {{4}}. Please bring a valid ID and your booking reference. We look forward to seeing you!',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name', 'pickup_date'],
                'language_code' => 'en',
            ],
            [
                'key' => 'payment_confirmation',
                'name' => 'Payment Confirmation',
                'description' => 'Sent to the customer when a payment is received.',
                'template_name' => 'payment_confirmation',
                'header' => 'Payment Confirmation',
                'body' => 'Payment confirmed for booking {{2}}. Thank you, {{1}}! Your payment has been received and recorded.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_new_booking',
                'name' => 'Admin - New Booking Alert',
                'description' => 'Sent to the admin when a new booking is created, with branch and amount details.',
                'template_name' => 'admin_booking_alert',
                'header' => 'New Booking Alert',
                'body' => 'New booking {{1}} from {{2}} branch. Customer: {{3}}. Vehicle: {{4}}. Total amount: {{5}}. Please review and confirm in the management portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'branch_name', 'customer_name', 'vehicle_name', 'total_amount'],
                'language_code' => 'en',
            ],
            [
                'key' => 'rental_cancelled',
                'name' => 'Rental Cancelled',
                'description' => 'Sent to the customer when a rental booking is cancelled.',
                'template_name' => 'rental_cancelled',
                'header' => 'Rental Cancelled',
                'body' => 'Hi {{1}}, your rental booking {{2}} for {{3}} has been cancelled. If you have any questions, please contact us.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'rental_status_change',
                'name' => 'Rental Status Update',
                'description' => 'Sent to the customer when their rental booking status changes.',
                'template_name' => 'rental_status_change',
                'header' => 'Booking Status Updated',
                'body' => 'Hi {{1}}, your rental booking {{2}} for {{3}} has been updated to {{4}}. Contact us if you have any questions.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'vehicle_name', 'new_status'],
                'language_code' => 'en',
            ],
            [
                'key' => 'airport_booking',
                'name' => 'Airport Transfer Confirmation',
                'description' => 'Sent to the customer when a new airport transfer booking is created.',
                'template_name' => 'airport_booking_confirmation',
                'header' => 'Transfer Booking Confirmed',
                'body' => 'Hi {{1}}, your airport transfer booking {{2}} has been received and is scheduled for {{3}}. We will confirm shortly.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'scheduled_at'],
                'language_code' => 'en',
            ],
            [
                'key' => 'airport_booking_cancelled',
                'name' => 'Airport Transfer Cancelled',
                'description' => 'Sent to the customer when an airport transfer booking is cancelled.',
                'template_name' => 'airport_booking_cancelled',
                'header' => 'Transfer Booking Cancelled',
                'body' => 'Hi {{1}}, your airport transfer booking {{2}} has been cancelled. If you have any questions, please contact us.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference'],
                'language_code' => 'en',
            ],
            [
                'key' => 'airport_booking_status_changed',
                'name' => 'Airport Booking Status Update',
                'description' => 'Sent to the admin when an airport booking status changes.',
                'template_name' => 'airport_booking_status_update',
                'header' => 'Booking Status Update',
                'body' => 'Airport booking {{1}} status updated to {{2}}. Please review in the management portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'new_status'],
                'language_code' => 'en',
            ],
            [
                'key' => 'chauffeur_booking',
                'name' => 'Chauffeur Booking Confirmation',
                'description' => 'Sent to the customer when a new chauffeur booking is created.',
                'template_name' => 'chauffeur_booking_confirmation',
                'header' => 'Chauffeur Booking Confirmed',
                'body' => 'Hi {{1}}, your chauffeur booking {{2}} has been received. Pickup: {{3}}. Vehicle: {{4}}. We will confirm shortly.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'pickup_time', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'chauffeur_booking_cancelled',
                'name' => 'Chauffeur Booking Cancelled',
                'description' => 'Sent to the customer when a chauffeur booking is cancelled.',
                'template_name' => 'chauffeur_booking_cancelled',
                'header' => 'Chauffeur Booking Cancelled',
                'body' => 'Hi {{1}}, your chauffeur booking {{2}} has been cancelled. If you have any questions, please contact us.',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference'],
                'language_code' => 'en',
            ],
            [
                'key' => 'chauffeur_booking_status_changed',
                'name' => 'Chauffeur Booking Status Update',
                'description' => 'Sent to the admin when a chauffeur booking status changes.',
                'template_name' => 'chauffeur_booking_status_update',
                'header' => 'Booking Status Update',
                'body' => 'Chauffeur booking {{1}} status updated to {{2}}. Please review in the management portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'new_status'],
                'language_code' => 'en',
            ],
            [
                'key' => 'chauffeur_pickup_reminder',
                'name' => 'Chauffeur Pickup Reminder',
                'description' => 'Sent to the customer as a reminder of their upcoming chauffeur pickup.',
                'template_name' => 'chauffeur_pickup_reminder',
                'header' => 'Pickup Reminder',
                'body' => 'Reminder: Your chauffeur booking {{2}} ({{4}}) has a pickup scheduled for {{3}}. We look forward to serving you!',
                'footer' => null,
                'variables' => ['customer_name', 'booking_reference', 'pickup_time', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'driver_document_expiry',
                'name' => 'Driver Document Expiry Alert',
                'description' => 'Sent to the admin when a driver document is expiring soon.',
                'template_name' => 'driver_document_expiry',
                'header' => 'Document Expiry Alert',
                'body' => 'Alert: Driver {{1}} has an expiring {{2}} on {{3}}. Please ensure the document is renewed before the expiry date.',
                'footer' => null,
                'variables' => ['driver_name', 'document_type', 'expiry_date'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_rental_cancelled',
                'name' => 'Admin - Rental Cancelled Alert',
                'description' => 'Sent to the admin when a rental booking is cancelled.',
                'template_name' => 'admin_rental_cancelled',
                'header' => 'Rental Cancelled',
                'body' => 'Booking {{1}} cancelled for {{2}} (branch {{3}}). Vehicle: {{4}}. Review in portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'customer_name', 'branch_name', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_pickup_reminder',
                'name' => 'Admin - Pickup Reminder',
                'description' => 'Sent to the admin for an upcoming rental pickup tomorrow.',
                'template_name' => 'admin_pickup_reminder',
                'header' => 'Pickup Tomorrow',
                'body' => 'Pickup tomorrow: {{1}} on {{2}}. Customer: {{3}}. Vehicle: {{4}}. Branch: {{5}}.',
                'footer' => null,
                'variables' => ['booking_reference', 'pickup_date', 'customer_name', 'vehicle_name', 'branch_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_return_reminder',
                'name' => 'Admin - Return Reminder',
                'description' => 'Sent to the admin for an upcoming rental return tomorrow.',
                'template_name' => 'admin_return_reminder',
                'header' => 'Return Tomorrow',
                'body' => 'Return tomorrow: {{1}} on {{2}}. Customer: {{3}}. Vehicle: {{4}}. Branch: {{5}}.',
                'footer' => null,
                'variables' => ['booking_reference', 'return_date', 'customer_name', 'vehicle_name', 'branch_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_overdue_alert',
                'name' => 'Admin - Overdue Alert',
                'description' => 'Sent to the admin when a rental becomes overdue.',
                'template_name' => 'admin_overdue_alert',
                'header' => 'Overdue Rental',
                'body' => 'OVERDUE: Booking {{1}} past return. Customer {{2}}, vehicle {{3}}, branch {{4}}. Action required.',
                'footer' => null,
                'variables' => ['booking_reference', 'customer_name', 'vehicle_name', 'branch_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_payment_confirmation',
                'name' => 'Admin - Payment Confirmed',
                'description' => 'Sent to the admin when a rental payment is confirmed.',
                'template_name' => 'admin_payment_confirmation',
                'header' => 'Payment Received',
                'body' => 'Payment of {{1}} received for booking {{2}} (customer {{3}}, branch {{4}}). Recorded in portal.',
                'footer' => null,
                'variables' => ['total_amount', 'booking_reference', 'customer_name', 'branch_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_rental_status_change',
                'name' => 'Admin - Rental Status Change',
                'description' => 'Sent to the admin when a rental status changes.',
                'template_name' => 'admin_rental_status_change',
                'header' => 'Booking Status Updated',
                'body' => 'Booking {{1}} status changed to {{2}}. Branch: {{3}}. Review in portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'new_status', 'branch_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_airport_booking',
                'name' => 'Admin - New Airport Booking',
                'description' => 'Sent to the admin when a new airport transfer booking is created.',
                'template_name' => 'admin_airport_booking',
                'header' => 'New Airport Transfer',
                'body' => 'New airport booking {{1}} at {{2}} branch. Customer: {{3}}. Vehicle: {{4}}. Review in portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'branch_name', 'customer_name', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_airport_booking_cancelled',
                'name' => 'Admin - Airport Booking Cancelled',
                'description' => 'Sent to the admin when an airport transfer booking is cancelled.',
                'template_name' => 'admin_airport_booking_cancelled',
                'header' => 'Airport Transfer Cancelled',
                'body' => 'Airport booking {{1}} cancelled by/for {{2}} (branch {{3}}). Vehicle: {{4}}.',
                'footer' => null,
                'variables' => ['booking_reference', 'customer_name', 'branch_name', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_chauffeur_booking',
                'name' => 'Admin - New Chauffeur Booking',
                'description' => 'Sent to the admin when a new chauffeur booking is created.',
                'template_name' => 'admin_chauffeur_booking',
                'header' => 'New Chauffeur Booking',
                'body' => 'New chauffeur booking {{1}} at {{2}} branch. Customer: {{3}}. Vehicle: {{4}}. Review in portal.',
                'footer' => null,
                'variables' => ['booking_reference', 'branch_name', 'customer_name', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_chauffeur_booking_cancelled',
                'name' => 'Admin - Chauffeur Booking Cancelled',
                'description' => 'Sent to the admin when a chauffeur booking is cancelled.',
                'template_name' => 'admin_chauffeur_booking_cancelled',
                'header' => 'Chauffeur Booking Cancelled',
                'body' => 'Chauffeur booking {{1}} cancelled by/for {{2}} (branch {{3}}). Vehicle: {{4}}.',
                'footer' => null,
                'variables' => ['booking_reference', 'customer_name', 'branch_name', 'vehicle_name'],
                'language_code' => 'en',
            ],
            [
                'key' => 'admin_chauffeur_pickup_reminder',
                'name' => 'Admin - Chauffeur Pickup Reminder',
                'description' => 'Sent to the admin for an upcoming chauffeur pickup tomorrow.',
                'template_name' => 'admin_chauffeur_pickup_reminder',
                'header' => 'Chauffeur Pickup Tomorrow',
                'body' => 'Chauffeur pickup tomorrow: {{1}} on {{2}}. Customer: {{3}}. Vehicle: {{4}}. Branch: {{5}}.',
                'footer' => null,
                'variables' => ['booking_reference', 'pickup_date', 'customer_name', 'vehicle_name', 'branch_name'],
                'language_code' => 'en',
            ],
        ];

        foreach ($templates as $template) {
            WhatsAppTemplate::query()->updateOrCreate(
                ['key' => $template['key']],
                array_merge($template, [
                    'default_template_name' => $template['template_name'],
                    'default_header' => $template['header'],
                    'default_body' => $template['body'],
                    'default_footer' => $template['footer'],
                    'default_variables' => $template['variables'],
                ])
            );
        }
    }
}
