<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class ActivityLogsExport implements FromCollection, ShouldAutoSize, WithEvents, WithHeadings, WithMapping, WithProperties, WithStyles, WithTitle
{
    public function __construct(
        protected Collection $logs,
    ) {}

    public function collection(): Collection
    {
        return $this->logs;
    }

    public function title(): string
    {
        return 'Activity Logs';
    }

    public function properties(): array
    {
        return [
            'creator' => config('app.name'),
            'company' => config('app.name'),
            'title' => 'Activity Logs Export',
            'description' => 'Generated by ' . config('app.name'),
        ];
    }

    public function headings(): array
    {
        return [
            'ID',
            'Event',
            'Description',
            'Subject',
            'Performed By',
            'Date',
        ];
    }

    /**
     * @param  \Spatie\Activitylog\Models\Activity  $log
     */
    public function map($log): array
    {
        return [
            $log->id,
            $log->log_name,
            $log->description,
            $log->subject_type ? class_basename($log->subject_type) : '-',
            $log->causer?->name ?? 'System',
            $log->created_at?->format('Y-m-d H:i'),
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            3 => ['font' => ['bold' => true]],
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => static function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $lastCol = 'F'; // 6 columns

                $sheet->insertNewRowBefore(1, 2);

                $sheet->setCellValue('A1', config('app.name') . ' - Activity Logs Export');
                $sheet->setCellValue('A2', 'Generated: ' . now()->format('Y-m-d H:i'));

                $sheet->mergeCells("A1:{$lastCol}1");
                $sheet->mergeCells("A2:{$lastCol}2");

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');
                $sheet->getStyle('A2')->getFont()->setItalic(true)->setSize(10);
                $sheet->getStyle('A2')->getAlignment()->setHorizontal('center');
            },
        ];
    }
}
