<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class CustomersExport implements FromCollection, ShouldAutoSize, WithEvents, WithHeadings, WithMapping, WithProperties, WithStyles, WithTitle
{
    public function __construct(
        protected Collection $customers,
    ) {}

    public function collection(): Collection
    {
        return $this->customers;
    }

    public function title(): string
    {
        return 'Customers';
    }

    public function properties(): array
    {
        return [
            'creator' => config('app.name'),
            'company' => config('app.name'),
            'title' => 'Customers Export',
            'description' => 'Generated by ' . config('app.name'),
        ];
    }

    public function headings(): array
    {
        return [
            'ID',
            'Name',
            'Email',
            'Phone',
            'ID Type',
            'ID Number',
            'License Number',
            'License Expiry',
            'Is Blacklisted',
            'Total Rentals',
            'Created At',
        ];
    }

    /**
     * @param  \App\Models\Customer  $customer
     */
    public function map($customer): array
    {
        return [
            $customer->id,
            $customer->name,
            $customer->email,
            $customer->phone,
            $customer->id_type?->value ?? $customer->id_type,
            $customer->id_number,
            $customer->license_number,
            $customer->license_expiry?->format('Y-m-d'),
            $customer->is_blacklisted ? 'Yes' : 'No',
            $customer->rentals_count ?? 0,
            $customer->created_at?->format('Y-m-d H:i'),
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            // Row 1 = site name header (inserted by AfterSheet), Row 2 = date, Row 3 = column headings
            3 => ['font' => ['bold' => true]],
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => static function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $lastCol = 'K'; // 11 columns

                $sheet->insertNewRowBefore(1, 2);

                $sheet->setCellValue('A1', config('app.name') . ' - Customers Export');
                $sheet->setCellValue('A2', 'Generated: ' . now()->format('Y-m-d H:i'));

                $sheet->mergeCells("A1:{$lastCol}1");
                $sheet->mergeCells("A2:{$lastCol}2");

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');
                $sheet->getStyle('A2')->getFont()->setItalic(true)->setSize(10);
                $sheet->getStyle('A2')->getAlignment()->setHorizontal('center');
            },
        ];
    }
}
