<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class RentalsExport implements FromCollection, ShouldAutoSize, WithEvents, WithHeadings, WithMapping, WithProperties, WithStyles, WithTitle
{
    public function __construct(
        protected Collection $rentals,
    ) {}

    public function collection(): Collection
    {
        return $this->rentals;
    }

    public function title(): string
    {
        return 'Rentals';
    }

    public function properties(): array
    {
        return [
            'creator' => config('app.name'),
            'company' => config('app.name'),
            'title' => 'Rentals Export',
            'description' => 'Generated by ' . config('app.name'),
        ];
    }

    public function headings(): array
    {
        return [
            'ID',
            'Reference',
            'Customer',
            'Vehicle',
            'Status',
            'Payment Status',
            'Pickup Date',
            'Return Date',
            'Total Cost',
            'Amount Paid',
            'Source',
            'Created At',
        ];
    }

    /**
     * @param  \App\Models\Rental  $rental
     */
    public function map($rental): array
    {
        return [
            $rental->id,
            $rental->reference,
            $rental->customer?->name ?? '-',
            $rental->vehicle?->name ?? '-',
            $rental->status?->value ?? $rental->status,
            $rental->payment_status?->value ?? $rental->payment_status,
            $rental->pickup_date?->format('Y-m-d'),
            $rental->return_date?->format('Y-m-d'),
            $rental->total_cost,
            $rental->amount_paid,
            $rental->source,
            $rental->created_at?->format('Y-m-d H:i'),
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            3 => ['font' => ['bold' => true]],
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => static function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $lastCol = 'L'; // 12 columns

                $sheet->insertNewRowBefore(1, 2);

                $sheet->setCellValue('A1', config('app.name') . ' - Rentals Export');
                $sheet->setCellValue('A2', 'Generated: ' . now()->format('Y-m-d H:i'));

                $sheet->mergeCells("A1:{$lastCol}1");
                $sheet->mergeCells("A2:{$lastCol}2");

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');
                $sheet->getStyle('A2')->getFont()->setItalic(true)->setSize(10);
                $sheet->getStyle('A2')->getAlignment()->setHorizontal('center');
            },
        ];
    }
}
