<?php

namespace App\Exports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\WithProperties;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class VehiclesExport implements FromCollection, ShouldAutoSize, WithEvents, WithHeadings, WithMapping, WithProperties, WithStyles, WithTitle
{
    public function __construct(
        protected Collection $vehicles,
    ) {}

    public function collection(): Collection
    {
        return $this->vehicles;
    }

    public function title(): string
    {
        return 'Vehicles';
    }

    public function properties(): array
    {
        return [
            'creator' => config('app.name'),
            'company' => config('app.name'),
            'title' => 'Vehicles Export',
            'description' => 'Generated by ' . config('app.name'),
        ];
    }

    public function headings(): array
    {
        return [
            'ID',
            'Name',
            'Category',
            'License Plate',
            'Make',
            'Model',
            'Year',
            'Color',
            'Fuel Type',
            'Transmission',
            'Status',
            'Daily Rate',
            'Total Rentals',
            'Is Featured',
        ];
    }

    /**
     * @param  \App\Models\Vehicle  $vehicle
     */
    public function map($vehicle): array
    {
        return [
            $vehicle->id,
            $vehicle->name,
            $vehicle->category?->name ?? 'N/A',
            $vehicle->license_plate,
            $vehicle->make,
            $vehicle->model,
            $vehicle->year,
            $vehicle->color,
            $vehicle->fuel_type?->value ?? $vehicle->fuel_type,
            $vehicle->transmission?->value ?? $vehicle->transmission,
            $vehicle->status?->value ?? $vehicle->status,
            number_format((float) $vehicle->daily_rate, 2),
            $vehicle->rentals_count ?? 0,
            $vehicle->is_featured ? 'Yes' : 'No',
        ];
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            3 => ['font' => ['bold' => true]],
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => static function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $lastCol = 'N'; // 14 columns

                $sheet->insertNewRowBefore(1, 2);

                $sheet->setCellValue('A1', config('app.name') . ' - Vehicles Export');
                $sheet->setCellValue('A2', 'Generated: ' . now()->format('Y-m-d H:i'));

                $sheet->mergeCells("A1:{$lastCol}1");
                $sheet->mergeCells("A2:{$lastCol}2");

                $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(13);
                $sheet->getStyle('A1')->getAlignment()->setHorizontal('center');
                $sheet->getStyle('A2')->getFont()->setItalic(true)->setSize(10);
                $sheet->getStyle('A2')->getAlignment()->setHorizontal('center');
            },
        ];
    }
}
