<?php

namespace App\Providers;

use App\Services\AdditionalChargeService;
use App\Services\AirportBookingService;
use App\Services\AirportCancellationSettingsService;
use App\Services\AirportCustomerService;
use App\Services\AirportLocationService;
use App\Services\AirportPackageAssignmentService;
use App\Services\AirportPackageService;
use App\Services\AirportPricingService;
use App\Services\AirportService;
use App\Services\AuthService;
use App\Services\BranchService;
use App\Services\CategoryService;
use App\Services\ChauffeurBookingService;
use App\Services\ChauffeurCustomerService;
use App\Services\ChauffeurLocationService;
use App\Services\ChauffeurPricingService;
use App\Services\ChauffeurSettingsService;
use App\Services\Contracts\AdditionalChargeServiceInterface;
use App\Services\Contracts\AirportBookingServiceInterface;
use App\Services\Contracts\AirportCancellationSettingsServiceInterface;
use App\Services\Contracts\AirportCustomerServiceInterface;
use App\Services\Contracts\AirportLocationServiceInterface;
use App\Services\Contracts\AirportPackageAssignmentServiceInterface;
use App\Services\Contracts\AirportPackageServiceInterface;
use App\Services\Contracts\AirportPricingServiceInterface;
use App\Services\Contracts\AirportServiceInterface;
use App\Services\Contracts\AuthServiceInterface;
use App\Services\Contracts\BranchServiceInterface;
use App\Services\Contracts\CategoryServiceInterface;
use App\Services\Contracts\ChauffeurBookingServiceInterface;
use App\Services\Contracts\ChauffeurCustomerServiceInterface;
use App\Services\Contracts\ChauffeurLocationServiceInterface;
use App\Services\Contracts\ChauffeurPricingServiceInterface;
use App\Services\Contracts\ChauffeurSettingsServiceInterface;
use App\Services\Contracts\CustomerDocumentServiceInterface;
use App\Services\Contracts\CustomerServiceInterface;
use App\Services\Contracts\DashboardServiceInterface;
use App\Services\Contracts\DiscountCouponServiceInterface;
use App\Services\Contracts\DiscountRuleServiceInterface;
use App\Services\Contracts\DiscountUsageServiceInterface;
use App\Services\Contracts\DriverAvailabilityServiceInterface;
use App\Services\Contracts\DriverServiceInterface;
use App\Services\Contracts\EmailTemplateServiceInterface;
use App\Services\Contracts\EmailTestServiceInterface;
use App\Services\Contracts\ExportServiceInterface;
use App\Services\Contracts\FeatureServiceInterface;
use App\Services\Contracts\FleetVehicleServiceInterface;
use App\Services\Contracts\Notifications\NotificationChannelInterface;
use App\Services\Contracts\Notifications\SmsNotificationServiceInterface;
use App\Services\Contracts\Notifications\WhatsAppNotificationServiceInterface;
use App\Services\Contracts\NotificationServiceInterface;
use App\Services\Contracts\PaymentServiceInterface;
use App\Services\Contracts\PricingServiceInterface;
use App\Services\Contracts\ProfileServiceInterface;
use App\Services\Contracts\QuoteRequestServiceInterface;
use App\Services\Contracts\RentalLocationServiceInterface;
use App\Services\Contracts\RentalServiceInterface;
use App\Services\Contracts\ReportServiceInterface;
use App\Services\Contracts\SmsTemplateServiceInterface;
use App\Services\Contracts\SystemServiceInterface;
use App\Services\Contracts\TestNotificationServiceInterface;
use App\Services\Contracts\UserServiceInterface;
use App\Services\Contracts\VehicleAvailabilityServiceInterface;
use App\Services\Contracts\VehicleExpenseServiceInterface;
use App\Services\Contracts\VehicleImageServiceInterface;
use App\Services\Contracts\VehicleServiceInterface;
use App\Services\Contracts\WhatsAppTemplateServiceInterface;
use App\Services\CustomerDocumentService;
use App\Services\CustomerService;
use App\Services\DashboardService;
use App\Services\DiscountCouponService;
use App\Services\DiscountRuleService;
use App\Services\DiscountUsageService;
use App\Services\DriverAvailabilityService;
use App\Services\DriverService;
use App\Services\EmailTemplateService;
use App\Services\EmailTestService;
use App\Services\ExportService;
use App\Services\FeatureService;
use App\Services\FleetVehicleService;
use App\Services\Notifications\Channels\SmsChannel;
use App\Services\Notifications\SmsNotificationService;
use App\Services\Notifications\WhatsAppNotificationService;
use App\Services\NotificationService;
use App\Services\Payment\PaymentManager;
use App\Services\PaymentService;
use App\Services\PricingService;
use App\Services\ProfileService;
use App\Services\QuoteRequestService;
use App\Services\RentalLocationService;
use App\Services\RentalService;
use App\Services\ReportService;
use App\Services\SmsTemplateService;
use App\Services\SystemService;
use App\Services\TestNotificationService;
use App\Services\TusUpload\TusTempFileResolver;
use App\Services\TusUpload\TusUploadService;
use App\Services\UserService;
use App\Services\VehicleAvailabilityService;
use App\Services\VehicleExpenseService;
use App\Services\VehicleImageService;
use App\Services\VehicleService;
use App\Services\WhatsAppTemplateService;
use Illuminate\Support\ServiceProvider;

class ServiceClassServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->bind(AirportServiceInterface::class, AirportService::class);
        $this->app->bind(AirportLocationServiceInterface::class, AirportLocationService::class);
        $this->app->bind(AirportPricingServiceInterface::class, AirportPricingService::class);
        $this->app->bind(AirportCustomerServiceInterface::class, AirportCustomerService::class);
        $this->app->bind(AirportBookingServiceInterface::class, AirportBookingService::class);
        $this->app->bind(AirportPackageServiceInterface::class, AirportPackageService::class);
        $this->app->bind(AirportPackageAssignmentServiceInterface::class, AirportPackageAssignmentService::class);
        $this->app->bind(BranchServiceInterface::class, BranchService::class);
        $this->app->bind(AuthServiceInterface::class, AuthService::class);
        $this->app->bind(CustomerServiceInterface::class, CustomerService::class);
        $this->app->bind(VehicleServiceInterface::class, VehicleService::class);
        $this->app->bind(VehicleImageServiceInterface::class, VehicleImageService::class);
        $this->app->bind(CategoryServiceInterface::class, CategoryService::class);
        $this->app->bind(FeatureServiceInterface::class, FeatureService::class);
        $this->app->bind(CustomerDocumentServiceInterface::class, CustomerDocumentService::class);
        $this->app->bind(UserServiceInterface::class, UserService::class);
        $this->app->bind(NotificationServiceInterface::class, NotificationService::class);
        $this->app->bind(TestNotificationServiceInterface::class, TestNotificationService::class);
        $this->app->bind(ReportServiceInterface::class, ReportService::class);
        $this->app->bind(DashboardServiceInterface::class, DashboardService::class);
        $this->app->bind(ExportServiceInterface::class, ExportService::class);
        $this->app->bind(EmailTemplateServiceInterface::class, EmailTemplateService::class);
        $this->app->bind(WhatsAppTemplateServiceInterface::class, WhatsAppTemplateService::class);
        $this->app->bind(SmsTemplateServiceInterface::class, SmsTemplateService::class);
        $this->app->bind(VehicleExpenseServiceInterface::class, VehicleExpenseService::class);
        $this->app->bind(AdditionalChargeServiceInterface::class, AdditionalChargeService::class);
        $this->app->bind(RentalLocationServiceInterface::class, RentalLocationService::class);
        $this->app->bind(DiscountRuleServiceInterface::class, DiscountRuleService::class);
        $this->app->bind(DiscountCouponServiceInterface::class, DiscountCouponService::class);
        $this->app->bind(PricingServiceInterface::class, PricingService::class);
        $this->app->bind(RentalServiceInterface::class, RentalService::class);
        $this->app->bind(DriverServiceInterface::class, DriverService::class);
        $this->app->bind(DriverAvailabilityServiceInterface::class, DriverAvailabilityService::class);
        $this->app->bind(FleetVehicleServiceInterface::class, FleetVehicleService::class);
        $this->app->bind(QuoteRequestServiceInterface::class, QuoteRequestService::class);
        $this->app->bind(ChauffeurCustomerServiceInterface::class, ChauffeurCustomerService::class);
        $this->app->bind(ChauffeurLocationServiceInterface::class, ChauffeurLocationService::class);
        $this->app->bind(ChauffeurPricingServiceInterface::class, ChauffeurPricingService::class);
        $this->app->bind(ChauffeurBookingServiceInterface::class, ChauffeurBookingService::class);
        $this->app->bind(VehicleAvailabilityServiceInterface::class, VehicleAvailabilityService::class);
        $this->app->bind(ProfileServiceInterface::class, ProfileService::class);
        $this->app->bind(SystemServiceInterface::class, SystemService::class);
        $this->app->bind(AirportCancellationSettingsServiceInterface::class, AirportCancellationSettingsService::class);
        $this->app->bind(ChauffeurSettingsServiceInterface::class, ChauffeurSettingsService::class);
        $this->app->bind(DiscountUsageServiceInterface::class, DiscountUsageService::class);
        $this->app->bind(EmailTestServiceInterface::class, EmailTestService::class);
        $this->app->when(SmsNotificationService::class)
            ->needs(NotificationChannelInterface::class)
            ->give(SmsChannel::class);

        $this->app->bind(WhatsAppNotificationServiceInterface::class, WhatsAppNotificationService::class);
        $this->app->bind(SmsNotificationServiceInterface::class, SmsNotificationService::class);
        $this->app->singleton(PaymentManager::class);
        $this->app->bind(PaymentServiceInterface::class, PaymentService::class);
        $this->app->singleton(TusUploadService::class);
        $this->app->singleton(TusTempFileResolver::class);
    }

    public function boot(): void {}
}
